version: '2' 

services:
  app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    
